.TH "char" 3 "Mon Nov 12 2012" "Version 1.0" "EF2:Maxwell_DGM2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
char \- 
.PP
A MatLab character array\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
A MatLab character array\&. 

This class is an artificially created class in doxygen to allow more precise type declarations and represents string-like types\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for EF2:Maxwell_DGM2 from the source code\&.
