.TH "class_substitutes.c" 3 "Mon Nov 12 2012" "Version 1.0" "EF2:Maxwell_DGM2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
class_substitutes.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmatrix\fP"
.br
.RI "\fIA matlab matrix\&. \fP"
.ti -1c
.RI "class \fBsparsematrix\fP"
.br
.RI "\fIA matlab sparse matrix\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EF2:Maxwell_DGM2 from the source code\&.
