.TH "colvec" 3 "Mon Nov 12 2012" "Version 1.0" "EF2:Maxwell_DGM2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
colvec \- 
.PP
A matlab column vector\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
A matlab column vector\&. 

This class is an artificially created class in doxygen to allow more precise type declarations 

.SH "Author"
.PP 
Generated automatically by Doxygen for EF2:Maxwell_DGM2 from the source code\&.
