.TH "developers" 3 "Mon Nov 12 2012" "Version 1.0" "EF2:Maxwell_DGM2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
developers \- Desarrolladores EF2 
.SH "Ricardo Prato"
.PP
https://sites.google.com/site/clasesrp/ -Profesor tiempo completo -Universidad del Norte
.SH "Catalina Dominguez"
.PP
https://sites.google.com/site/catadomingu/ -Profesora tiempo completo -Universidad del Norte 
