.TH "Ece.m" 3 "Mon Nov 12 2012" "Version 1.0" "EF2:Maxwell_DGM2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ece.m \- 
.PP
Calcula el valor de la función exacta (dada en rhs) en el punto xs\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "mlhsInnerSubst
.br
< matlabtypesubstitute, Es > \fBEce\fP (matlabtypesubstitute t, matlabtypesubstitute xs, matlabtypesubstitute rhs)"
.br
.RI "\fICalcula el valor de la función exacta (dada en rhs) en el punto xs\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Calcula el valor de la función exacta (dada en rhs) en el punto xs\&. 


.SH "Function Documentation"
.PP 
.SS "mlhsInnerSubst< matlabtypesubstitute, Es > \fBEce\fP (matlabtypesubstitutet, matlabtypesubstitutexs, matlabtypesubstituterhs)"

.PP
Calcula el valor de la función exacta (dada en rhs) en el punto xs\&. \fBAuthor:\fP
.RS 4
Ricardo Prato 
.PP
Catalina Dominguez 
.RE
.PP
\fBDate:\fP
.RS 4
2012-03-30
.RE
.PP
\fBParameters:\fP
.RS 4
\fIt\fP tiempo 
.br
\fIxs\fP Punto 
.br
\fIrhs\fP Id\&. de la solución exacta
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIEs\fP Valor de la funcion exacta en xs\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for EF2:Maxwell_DGM2 from the source code\&.
