.TH "funciones.m" 3 "Mon Nov 12 2012" "Version 1.0" "EF2:Maxwell_DGM2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
funciones.m \- 
.PP
String de la función exacta utilizada\&. Por ejemplo,\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "mlhsInnerSubst
.br
< matlabtypesubstitute, value > \fBfunciones\fP (matlabtypesubstitute rhs)"
.br
.RI "\fIString de la función exacta utilizada\&. Por ejemplo,\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
String de la función exacta utilizada\&. Por ejemplo,\&. 

.PP
.nf
 >> funciones(80)  
.fi
.PP
 
.PP
.nf
     E:=sin(t)*[x*y * (1 - x) * (1 - y)),0]
.fi
.PP
 Parameters: rhs: Entero\&. Id\&. de la función exacta 
.SH "Function Documentation"
.PP 
.SS "mlhsInnerSubst< matlabtypesubstitute, value > \fBfunciones\fP (matlabtypesubstituterhs)"

.PP
String de la función exacta utilizada\&. Por ejemplo,\&. .PP
.nf
 >> funciones(80)  
.fi
.PP
 
.PP
.nf
     E:=sin(t)*[x*y * (1 - x) * (1 - y)),0]
.fi
.PP
 Parameters: rhs: Entero\&. Id\&. de la función exacta
.PP
\fBAuthor:\fP
.RS 4
Catalina Dominguez 
.RE
.PP
\fBDate:\fP
.RS 4
2012-03-25
.RE
.PP
\fBParameters:\fP
.RS 4
\fIrhs\fP rhs
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIvalue\fP String \&. Forma de la solución exacta 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for EF2:Maxwell_DGM2 from the source code\&.
