.TH "sparsematrix" 3 "Mon Nov 12 2012" "Version 1.0" "EF2:Maxwell_DGM2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sparsematrix \- 
.PP
A matlab sparse matrix\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBmatrix\fP\&.
.SH "Detailed Description"
.PP 
A matlab sparse matrix\&. 

This class is an artificially created class in doxygen to allow more precise type declarations 

.SH "Author"
.PP 
Generated automatically by Doxygen for EF2:Maxwell_DGM2 from the source code\&.
