.TH "varargout" 3 "Mon Nov 12 2012" "Version 1.0" "EF2:Maxwell_DGM2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
varargout \- 
.PP
A variable number of output arguments\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
A variable number of output arguments\&. 

This class is an artificially created class in doxygen to allow more precise type declarations\&.
.PP
For more information about the varargout argument see the \fCMatLab documentation on varargout\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for EF2:Maxwell_DGM2 from the source code\&.
